//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:15 PM COT 
//


package org.bilan.co.ws.sineb.establecimiento;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EstablecimientoEducativo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstablecimientoEducativo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codDane" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codDepartamento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codMunicipio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="direccion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="barrio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numTelefono" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="correo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codTipoEstablecimiento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codSectorEducativo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codSecretaria" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codResguardo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="lstCodEtnia" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="codPropiedadPlantaFisica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codPropiedadAdministrativa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codGeneroAtencion" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="lstCodCapacidadExcepcional" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lstCodDiscapacidad" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lstCodIdioma" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="codCaracterEducativo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="codCalendarioEducativo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="codRevisionLicencia" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="esMatriculaContratada" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="codEstado" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rector" type="{http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/}Rector" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstablecimientoEducativo", propOrder = {
    "codDane",
    "nombre",
    "codDepartamento",
    "codMunicipio",
    "direccion",
    "barrio",
    "numTelefono",
    "correo",
    "codTipoEstablecimiento",
    "codSectorEducativo",
    "codSecretaria",
    "codResguardo",
    "lstCodEtnia",
    "codPropiedadPlantaFisica",
    "codPropiedadAdministrativa",
    "codGeneroAtencion",
    "lstCodCapacidadExcepcional",
    "lstCodDiscapacidad",
    "lstCodIdioma",
    "codCaracterEducativo",
    "codCalendarioEducativo",
    "codRevisionLicencia",
    "esMatriculaContratada",
    "codEstado",
    "rector"
})
public class EstablecimientoEducativo {

    @XmlElement(required = true)
    protected String codDane;
    @XmlElement(required = true)
    protected String nombre;
    @XmlElement(required = true)
    protected String codDepartamento;
    @XmlElement(required = true)
    protected String codMunicipio;
    @XmlElement(required = true)
    protected String direccion;
    protected String barrio;
    protected String numTelefono;
    protected String correo;
    @XmlElement(required = true)
    protected String codTipoEstablecimiento;
    @XmlElement(required = true)
    protected String codSectorEducativo;
    @XmlElement(required = true)
    protected String codSecretaria;
    protected Integer codResguardo;
    @XmlElement(nillable = true)
    protected List<String> lstCodEtnia;
    @XmlElement(required = true)
    protected String codPropiedadPlantaFisica;
    @XmlElement(required = true)
    protected String codPropiedadAdministrativa;
    protected int codGeneroAtencion;
    @XmlElement(nillable = true)
    protected List<Integer> lstCodCapacidadExcepcional;
    @XmlElement(nillable = true)
    protected List<Integer> lstCodDiscapacidad;
    @XmlElement(nillable = true)
    protected List<Integer> lstCodIdioma;
    protected Integer codCaracterEducativo;
    protected int codCalendarioEducativo;
    protected int codRevisionLicencia;
    protected boolean esMatriculaContratada;
    protected int codEstado;
    protected Rector rector;

    /**
     * Gets the value of the codDane property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodDane() {
        return codDane;
    }

    /**
     * Sets the value of the codDane property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodDane(String value) {
        this.codDane = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the codDepartamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodDepartamento() {
        return codDepartamento;
    }

    /**
     * Sets the value of the codDepartamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodDepartamento(String value) {
        this.codDepartamento = value;
    }

    /**
     * Gets the value of the codMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodMunicipio() {
        return codMunicipio;
    }

    /**
     * Sets the value of the codMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodMunicipio(String value) {
        this.codMunicipio = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccion(String value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the barrio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarrio() {
        return barrio;
    }

    /**
     * Sets the value of the barrio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarrio(String value) {
        this.barrio = value;
    }

    /**
     * Gets the value of the numTelefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumTelefono() {
        return numTelefono;
    }

    /**
     * Sets the value of the numTelefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumTelefono(String value) {
        this.numTelefono = value;
    }

    /**
     * Gets the value of the correo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * Sets the value of the correo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorreo(String value) {
        this.correo = value;
    }

    /**
     * Gets the value of the codTipoEstablecimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodTipoEstablecimiento() {
        return codTipoEstablecimiento;
    }

    /**
     * Sets the value of the codTipoEstablecimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodTipoEstablecimiento(String value) {
        this.codTipoEstablecimiento = value;
    }

    /**
     * Gets the value of the codSectorEducativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodSectorEducativo() {
        return codSectorEducativo;
    }

    /**
     * Sets the value of the codSectorEducativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodSectorEducativo(String value) {
        this.codSectorEducativo = value;
    }

    /**
     * Gets the value of the codSecretaria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodSecretaria() {
        return codSecretaria;
    }

    /**
     * Sets the value of the codSecretaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodSecretaria(String value) {
        this.codSecretaria = value;
    }

    /**
     * Gets the value of the codResguardo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodResguardo() {
        return codResguardo;
    }

    /**
     * Sets the value of the codResguardo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodResguardo(Integer value) {
        this.codResguardo = value;
    }

    /**
     * Gets the value of the lstCodEtnia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lstCodEtnia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLstCodEtnia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLstCodEtnia() {
        if (lstCodEtnia == null) {
            lstCodEtnia = new ArrayList<String>();
        }
        return this.lstCodEtnia;
    }

    /**
     * Gets the value of the codPropiedadPlantaFisica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPropiedadPlantaFisica() {
        return codPropiedadPlantaFisica;
    }

    /**
     * Sets the value of the codPropiedadPlantaFisica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPropiedadPlantaFisica(String value) {
        this.codPropiedadPlantaFisica = value;
    }

    /**
     * Gets the value of the codPropiedadAdministrativa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPropiedadAdministrativa() {
        return codPropiedadAdministrativa;
    }

    /**
     * Sets the value of the codPropiedadAdministrativa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPropiedadAdministrativa(String value) {
        this.codPropiedadAdministrativa = value;
    }

    /**
     * Gets the value of the codGeneroAtencion property.
     * 
     */
    public int getCodGeneroAtencion() {
        return codGeneroAtencion;
    }

    /**
     * Sets the value of the codGeneroAtencion property.
     * 
     */
    public void setCodGeneroAtencion(int value) {
        this.codGeneroAtencion = value;
    }

    /**
     * Gets the value of the lstCodCapacidadExcepcional property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lstCodCapacidadExcepcional property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLstCodCapacidadExcepcional().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getLstCodCapacidadExcepcional() {
        if (lstCodCapacidadExcepcional == null) {
            lstCodCapacidadExcepcional = new ArrayList<Integer>();
        }
        return this.lstCodCapacidadExcepcional;
    }

    /**
     * Gets the value of the lstCodDiscapacidad property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lstCodDiscapacidad property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLstCodDiscapacidad().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getLstCodDiscapacidad() {
        if (lstCodDiscapacidad == null) {
            lstCodDiscapacidad = new ArrayList<Integer>();
        }
        return this.lstCodDiscapacidad;
    }

    /**
     * Gets the value of the lstCodIdioma property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lstCodIdioma property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLstCodIdioma().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getLstCodIdioma() {
        if (lstCodIdioma == null) {
            lstCodIdioma = new ArrayList<Integer>();
        }
        return this.lstCodIdioma;
    }

    /**
     * Gets the value of the codCaracterEducativo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodCaracterEducativo() {
        return codCaracterEducativo;
    }

    /**
     * Sets the value of the codCaracterEducativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodCaracterEducativo(Integer value) {
        this.codCaracterEducativo = value;
    }

    /**
     * Gets the value of the codCalendarioEducativo property.
     * 
     */
    public int getCodCalendarioEducativo() {
        return codCalendarioEducativo;
    }

    /**
     * Sets the value of the codCalendarioEducativo property.
     * 
     */
    public void setCodCalendarioEducativo(int value) {
        this.codCalendarioEducativo = value;
    }

    /**
     * Gets the value of the codRevisionLicencia property.
     * 
     */
    public int getCodRevisionLicencia() {
        return codRevisionLicencia;
    }

    /**
     * Sets the value of the codRevisionLicencia property.
     * 
     */
    public void setCodRevisionLicencia(int value) {
        this.codRevisionLicencia = value;
    }

    /**
     * Gets the value of the esMatriculaContratada property.
     * 
     */
    public boolean isEsMatriculaContratada() {
        return esMatriculaContratada;
    }

    /**
     * Sets the value of the esMatriculaContratada property.
     * 
     */
    public void setEsMatriculaContratada(boolean value) {
        this.esMatriculaContratada = value;
    }

    /**
     * Gets the value of the codEstado property.
     * 
     */
    public int getCodEstado() {
        return codEstado;
    }

    /**
     * Sets the value of the codEstado property.
     * 
     */
    public void setCodEstado(int value) {
        this.codEstado = value;
    }

    /**
     * Gets the value of the rector property.
     * 
     * @return
     *     possible object is
     *     {@link Rector }
     *     
     */
    public Rector getRector() {
        return rector;
    }

    /**
     * Sets the value of the rector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rector }
     *     
     */
    public void setRector(Rector value) {
        this.rector = value;
    }

}
