//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:15 PM COT 
//


package org.bilan.co.ws.sineb.establecimiento;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FiltroEstablecimientosEducativos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiltroEstablecimientosEducativos"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codDepartamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codMunicipio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codTipoEstablecimiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codSectorEducativo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codSecretaria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codResguardo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="codPropiedadPlantaFisica" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codPropiedadAdministrativa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codGeneroAtencion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="codCaracterEducativo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="codCalendarioEducativo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="codEstados" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="paginacion" type="{http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/}FiltroPaginacion"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiltroEstablecimientosEducativos", propOrder = {
    "nombre",
    "codDepartamento",
    "codMunicipio",
    "codTipoEstablecimiento",
    "codSectorEducativo",
    "codSecretaria",
    "codResguardo",
    "codPropiedadPlantaFisica",
    "codPropiedadAdministrativa",
    "codGeneroAtencion",
    "codCaracterEducativo",
    "codCalendarioEducativo",
    "codEstados",
    "paginacion"
})
public class FiltroEstablecimientosEducativos {

    protected String nombre;
    protected String codDepartamento;
    protected String codMunicipio;
    protected String codTipoEstablecimiento;
    protected String codSectorEducativo;
    protected String codSecretaria;
    protected Integer codResguardo;
    protected String codPropiedadPlantaFisica;
    protected String codPropiedadAdministrativa;
    protected Integer codGeneroAtencion;
    protected Integer codCaracterEducativo;
    protected Integer codCalendarioEducativo;
    @XmlElement(nillable = true)
    protected List<Integer> codEstados;
    @XmlElement(required = true)
    protected FiltroPaginacion paginacion;

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the codDepartamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodDepartamento() {
        return codDepartamento;
    }

    /**
     * Sets the value of the codDepartamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodDepartamento(String value) {
        this.codDepartamento = value;
    }

    /**
     * Gets the value of the codMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodMunicipio() {
        return codMunicipio;
    }

    /**
     * Sets the value of the codMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodMunicipio(String value) {
        this.codMunicipio = value;
    }

    /**
     * Gets the value of the codTipoEstablecimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodTipoEstablecimiento() {
        return codTipoEstablecimiento;
    }

    /**
     * Sets the value of the codTipoEstablecimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodTipoEstablecimiento(String value) {
        this.codTipoEstablecimiento = value;
    }

    /**
     * Gets the value of the codSectorEducativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodSectorEducativo() {
        return codSectorEducativo;
    }

    /**
     * Sets the value of the codSectorEducativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodSectorEducativo(String value) {
        this.codSectorEducativo = value;
    }

    /**
     * Gets the value of the codSecretaria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodSecretaria() {
        return codSecretaria;
    }

    /**
     * Sets the value of the codSecretaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodSecretaria(String value) {
        this.codSecretaria = value;
    }

    /**
     * Gets the value of the codResguardo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodResguardo() {
        return codResguardo;
    }

    /**
     * Sets the value of the codResguardo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodResguardo(Integer value) {
        this.codResguardo = value;
    }

    /**
     * Gets the value of the codPropiedadPlantaFisica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPropiedadPlantaFisica() {
        return codPropiedadPlantaFisica;
    }

    /**
     * Sets the value of the codPropiedadPlantaFisica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPropiedadPlantaFisica(String value) {
        this.codPropiedadPlantaFisica = value;
    }

    /**
     * Gets the value of the codPropiedadAdministrativa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPropiedadAdministrativa() {
        return codPropiedadAdministrativa;
    }

    /**
     * Sets the value of the codPropiedadAdministrativa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPropiedadAdministrativa(String value) {
        this.codPropiedadAdministrativa = value;
    }

    /**
     * Gets the value of the codGeneroAtencion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodGeneroAtencion() {
        return codGeneroAtencion;
    }

    /**
     * Sets the value of the codGeneroAtencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodGeneroAtencion(Integer value) {
        this.codGeneroAtencion = value;
    }

    /**
     * Gets the value of the codCaracterEducativo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodCaracterEducativo() {
        return codCaracterEducativo;
    }

    /**
     * Sets the value of the codCaracterEducativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodCaracterEducativo(Integer value) {
        this.codCaracterEducativo = value;
    }

    /**
     * Gets the value of the codCalendarioEducativo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodCalendarioEducativo() {
        return codCalendarioEducativo;
    }

    /**
     * Sets the value of the codCalendarioEducativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodCalendarioEducativo(Integer value) {
        this.codCalendarioEducativo = value;
    }

    /**
     * Gets the value of the codEstados property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codEstados property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodEstados().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getCodEstados() {
        if (codEstados == null) {
            codEstados = new ArrayList<Integer>();
        }
        return this.codEstados;
    }

    /**
     * Gets the value of the paginacion property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroPaginacion }
     *     
     */
    public FiltroPaginacion getPaginacion() {
        return paginacion;
    }

    /**
     * Sets the value of the paginacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroPaginacion }
     *     
     */
    public void setPaginacion(FiltroPaginacion value) {
        this.paginacion = value;
    }

}
