//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:15 PM COT 
//


package org.bilan.co.ws.sineb.establecimiento;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for obtenerEstablecimientosEducativos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="obtenerEstablecimientosEducativos"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="filtroEstablecimientosEducativos" type="{http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/}FiltroEstablecimientosEducativos" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerEstablecimientosEducativos", propOrder = {
    "filtroEstablecimientosEducativos"
})
public class ObtenerEstablecimientosEducativos {

    protected FiltroEstablecimientosEducativos filtroEstablecimientosEducativos;

    /**
     * Gets the value of the filtroEstablecimientosEducativos property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroEstablecimientosEducativos }
     *     
     */
    public FiltroEstablecimientosEducativos getFiltroEstablecimientosEducativos() {
        return filtroEstablecimientosEducativos;
    }

    /**
     * Sets the value of the filtroEstablecimientosEducativos property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroEstablecimientosEducativos }
     *     
     */
    public void setFiltroEstablecimientosEducativos(FiltroEstablecimientosEducativos value) {
        this.filtroEstablecimientosEducativos = value;
    }

}
