//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:15 PM COT 
//


package org.bilan.co.ws.sineb.establecimiento;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Paginacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Paginacion"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="totalRegistros" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="totalPaginas" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="totalRegistrosPorPagina" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="numeroPagina" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Paginacion", propOrder = {
    "totalRegistros",
    "totalPaginas",
    "totalRegistrosPorPagina",
    "numeroPagina"
})
public class Paginacion {

    protected int totalRegistros;
    protected int totalPaginas;
    protected int totalRegistrosPorPagina;
    protected int numeroPagina;

    /**
     * Gets the value of the totalRegistros property.
     * 
     */
    public int getTotalRegistros() {
        return totalRegistros;
    }

    /**
     * Sets the value of the totalRegistros property.
     * 
     */
    public void setTotalRegistros(int value) {
        this.totalRegistros = value;
    }

    /**
     * Gets the value of the totalPaginas property.
     * 
     */
    public int getTotalPaginas() {
        return totalPaginas;
    }

    /**
     * Sets the value of the totalPaginas property.
     * 
     */
    public void setTotalPaginas(int value) {
        this.totalPaginas = value;
    }

    /**
     * Gets the value of the totalRegistrosPorPagina property.
     * 
     */
    public int getTotalRegistrosPorPagina() {
        return totalRegistrosPorPagina;
    }

    /**
     * Sets the value of the totalRegistrosPorPagina property.
     * 
     */
    public void setTotalRegistrosPorPagina(int value) {
        this.totalRegistrosPorPagina = value;
    }

    /**
     * Gets the value of the numeroPagina property.
     * 
     */
    public int getNumeroPagina() {
        return numeroPagina;
    }

    /**
     * Sets the value of the numeroPagina property.
     * 
     */
    public void setNumeroPagina(int value) {
        this.numeroPagina = value;
    }

}
