//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:16 PM COT 
//


package org.bilan.co.ws.simat.matricula;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumCodEstadoEstudiante.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumCodEstadoEstudiante"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AS"/&gt;
 *     &lt;enumeration value="CAN"/&gt;
 *     &lt;enumeration value="GR"/&gt;
 *     &lt;enumeration value="INS"/&gt;
 *     &lt;enumeration value="MAT"/&gt;
 *     &lt;enumeration value="NUEV"/&gt;
 *     &lt;enumeration value="PMAT"/&gt;
 *     &lt;enumeration value="PROM"/&gt;
 *     &lt;enumeration value="REP"/&gt;
 *     &lt;enumeration value="RET"/&gt;
 *     &lt;enumeration value="SC"/&gt;
 *     &lt;enumeration value="SINASIG"/&gt;
 *     &lt;enumeration value="TR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "enumCodEstadoEstudiante", namespace = "http://www.mineducacion.gov.co/1.0/schemas/")
@XmlEnum
public enum EnumCodEstadoEstudiante {

    AS,
    CAN,
    GR,
    INS,
    MAT,
    NUEV,
    PMAT,
    PROM,
    REP,
    RET,
    SC,
    SINASIG,
    TR;

    public String value() {
        return name();
    }

    public static EnumCodEstadoEstudiante fromValue(String v) {
        return valueOf(v);
    }

}
