//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:16 PM COT 
//


package org.bilan.co.ws.simat.matricula;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identificacionPersona complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identificacionPersona"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identificacionPersona", namespace = "http://www.mineducacion.gov.co/1.0/schemas/")
@XmlSeeAlso({
    IdentificacionPersonaRC.class,
    IdentificacionPersonaTI.class,
    IdentificacionPersonaCC.class,
    IdentificacionPersonaCE.class,
    IdentificacionPersonaVISA.class,
    IdentificacionPersonaTMF.class,
    IdentificacionPersonaPEP.class,
    IdentificacionPersonaNES.class
})
public abstract class IdentificacionPersona {


}
