//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:16 PM COT 
//


package org.bilan.co.ws.simat.matricula;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Matricula complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Matricula"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identificacion" type="{http://www.mineducacion.gov.co/1.0/schemas/}identificacionPersona"/&gt;
 *         &lt;element name="annio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codSede" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codJornada" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="codModeloEducativo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codGradoEducativo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nomGrupo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codEstadoEstudiante" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaEstado" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="esSubsidiado" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="esRepitente" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="esNuevo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="situacionAnterior" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="provieneOtroMunicipio" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="provieneSectorPrivado" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Matricula", namespace = "http://www.mineducacion.gov.co/1.0/schemas/", propOrder = {
    "identificacion",
    "annio",
    "codSede",
    "codJornada",
    "codModeloEducativo",
    "codGradoEducativo",
    "nomGrupo",
    "codEstadoEstudiante",
    "fechaEstado",
    "esSubsidiado",
    "esRepitente",
    "esNuevo",
    "situacionAnterior",
    "provieneOtroMunicipio",
    "provieneSectorPrivado"
})
public class Matricula {

    @XmlElement(required = true)
    protected IdentificacionPersona identificacion;
    @XmlElement(required = true)
    protected String annio;
    @XmlElement(required = true)
    protected String codSede;
    protected int codJornada;
    @XmlElement(required = true)
    protected String codModeloEducativo;
    @XmlElement(required = true)
    protected String codGradoEducativo;
    protected String nomGrupo;
    @XmlElement(required = true)
    protected String codEstadoEstudiante;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaEstado;
    protected Boolean esSubsidiado;
    protected Boolean esRepitente;
    protected Boolean esNuevo;
    protected Integer situacionAnterior;
    protected Boolean provieneOtroMunicipio;
    protected Boolean provieneSectorPrivado;

    /**
     * Gets the value of the identificacion property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificacionPersona }
     *     
     */
    public IdentificacionPersona getIdentificacion() {
        return identificacion;
    }

    /**
     * Sets the value of the identificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificacionPersona }
     *     
     */
    public void setIdentificacion(IdentificacionPersona value) {
        this.identificacion = value;
    }

    /**
     * Gets the value of the annio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnio() {
        return annio;
    }

    /**
     * Sets the value of the annio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnio(String value) {
        this.annio = value;
    }

    /**
     * Gets the value of the codSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodSede() {
        return codSede;
    }

    /**
     * Sets the value of the codSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodSede(String value) {
        this.codSede = value;
    }

    /**
     * Gets the value of the codJornada property.
     * 
     */
    public int getCodJornada() {
        return codJornada;
    }

    /**
     * Sets the value of the codJornada property.
     * 
     */
    public void setCodJornada(int value) {
        this.codJornada = value;
    }

    /**
     * Gets the value of the codModeloEducativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodModeloEducativo() {
        return codModeloEducativo;
    }

    /**
     * Sets the value of the codModeloEducativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodModeloEducativo(String value) {
        this.codModeloEducativo = value;
    }

    /**
     * Gets the value of the codGradoEducativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodGradoEducativo() {
        return codGradoEducativo;
    }

    /**
     * Sets the value of the codGradoEducativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodGradoEducativo(String value) {
        this.codGradoEducativo = value;
    }

    /**
     * Gets the value of the nomGrupo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomGrupo() {
        return nomGrupo;
    }

    /**
     * Sets the value of the nomGrupo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomGrupo(String value) {
        this.nomGrupo = value;
    }

    /**
     * Gets the value of the codEstadoEstudiante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodEstadoEstudiante() {
        return codEstadoEstudiante;
    }

    /**
     * Sets the value of the codEstadoEstudiante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodEstadoEstudiante(String value) {
        this.codEstadoEstudiante = value;
    }

    /**
     * Gets the value of the fechaEstado property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEstado() {
        return fechaEstado;
    }

    /**
     * Sets the value of the fechaEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEstado(XMLGregorianCalendar value) {
        this.fechaEstado = value;
    }

    /**
     * Gets the value of the esSubsidiado property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEsSubsidiado() {
        return esSubsidiado;
    }

    /**
     * Sets the value of the esSubsidiado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEsSubsidiado(Boolean value) {
        this.esSubsidiado = value;
    }

    /**
     * Gets the value of the esRepitente property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEsRepitente() {
        return esRepitente;
    }

    /**
     * Sets the value of the esRepitente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEsRepitente(Boolean value) {
        this.esRepitente = value;
    }

    /**
     * Gets the value of the esNuevo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEsNuevo() {
        return esNuevo;
    }

    /**
     * Sets the value of the esNuevo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEsNuevo(Boolean value) {
        this.esNuevo = value;
    }

    /**
     * Gets the value of the situacionAnterior property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSituacionAnterior() {
        return situacionAnterior;
    }

    /**
     * Sets the value of the situacionAnterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSituacionAnterior(Integer value) {
        this.situacionAnterior = value;
    }

    /**
     * Gets the value of the provieneOtroMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProvieneOtroMunicipio() {
        return provieneOtroMunicipio;
    }

    /**
     * Sets the value of the provieneOtroMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProvieneOtroMunicipio(Boolean value) {
        this.provieneOtroMunicipio = value;
    }

    /**
     * Gets the value of the provieneSectorPrivado property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProvieneSectorPrivado() {
        return provieneSectorPrivado;
    }

    /**
     * Sets the value of the provieneSectorPrivado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProvieneSectorPrivado(Boolean value) {
        this.provieneSectorPrivado = value;
    }

}
