//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:15 PM COT 
//


package org.bilan.co.ws.sineb.sedeeducativa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for obtenerSedesEducativas complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="obtenerSedesEducativas"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="filtroSedesEducativas" type="{http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/}FiltroSedesEducativas"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerSedesEducativas", propOrder = {
    "filtroSedesEducativas"
})
public class ObtenerSedesEducativas {

    @XmlElement(required = true)
    protected FiltroSedesEducativas filtroSedesEducativas;

    /**
     * Gets the value of the filtroSedesEducativas property.
     * 
     * @return
     *     possible object is
     *     {@link FiltroSedesEducativas }
     *     
     */
    public FiltroSedesEducativas getFiltroSedesEducativas() {
        return filtroSedesEducativas;
    }

    /**
     * Sets the value of the filtroSedesEducativas property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiltroSedesEducativas }
     *     
     */
    public void setFiltroSedesEducativas(FiltroSedesEducativas value) {
        this.filtroSedesEducativas = value;
    }

}
