//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:15 PM COT 
//


package org.bilan.co.ws.sineb.sedeeducativa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for obtenerSedeEducativaResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="obtenerSedeEducativaResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sedeEducativa" type="{http://serviciosImpl.wsstandardsineb.mineducacion.gov.co/}SedeEducativa" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerSedeEducativaResponse", propOrder = {
    "sedeEducativa"
})
public class ObtenerSedeEducativaResponse {

    protected SedeEducativa sedeEducativa;

    /**
     * Gets the value of the sedeEducativa property.
     * 
     * @return
     *     possible object is
     *     {@link SedeEducativa }
     *     
     */
    public SedeEducativa getSedeEducativa() {
        return sedeEducativa;
    }

    /**
     * Sets the value of the sedeEducativa property.
     * 
     * @param value
     *     allowed object is
     *     {@link SedeEducativa }
     *     
     */
    public void setSedeEducativa(SedeEducativa value) {
        this.sedeEducativa = value;
    }

}
