USE `bilan`;
INSERT INTO `courses` (`id`, `name`) VALUES (1, 'A');
INSERT INTO `courses` (`id`, `name`) VALUES (2, 'B');
INSERT INTO `courses` (`id`, `name`) VALUES (3, 'C');
INSERT INTO `courses` (`id`, `name`) VALUES (4, 'D');
INSERT INTO `courses` (`id`, `name`) VALUES (5, '1');
INSERT INTO `courses` (`id`, `name`) VALUES (6, '2');
INSERT INTO `courses` (`id`, `name`) VALUES (7, '3');
INSERT INTO `courses` (`id`, `name`) VALUES (8, '4');
INSERT INTO `courses` (`id`, `name`) VALUES (9, '01');
INSERT INTO `courses` (`id`, `name`) VALUES (10, '02');
INSERT INTO `courses` (`id`, `name`) VALUES (11, '03');
INSERT INTO `courses` (`id`, `name`) VALUES (12, '04');
