//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:18 PM COT 
//


package org.bilan.co.ws.simat.estudiante;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumCodTipoZonaUbicacion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumCodTipoZonaUbicacion"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="U"/&gt;
 *     &lt;enumeration value="R"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "enumCodTipoZonaUbicacion", namespace = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/Local/Ubicacion")
@XmlEnum
public enum EnumCodTipoZonaUbicacion {

    U,
    R;

    public String value() {
        return name();
    }

    public static EnumCodTipoZonaUbicacion fromValue(String v) {
        return valueOf(v);
    }

}
