//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 10:41:18 PM COT 
//


package org.bilan.co.ws.simat.estudiante;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="totalEstudiantes" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="totalGrupos" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalEstudiantes",
    "totalGrupos"
})
@XmlRootElement(name = "totalEstudiantesGrupos")
public class TotalEstudiantesGrupos {

    @XmlElement(namespace = "")
    protected int totalEstudiantes;
    @XmlElement(namespace = "")
    protected int totalGrupos;

    /**
     * Gets the value of the totalEstudiantes property.
     * 
     */
    public int getTotalEstudiantes() {
        return totalEstudiantes;
    }

    /**
     * Sets the value of the totalEstudiantes property.
     * 
     */
    public void setTotalEstudiantes(int value) {
        this.totalEstudiantes = value;
    }

    /**
     * Gets the value of the totalGrupos property.
     * 
     */
    public int getTotalGrupos() {
        return totalGrupos;
    }

    /**
     * Sets the value of the totalGrupos property.
     * 
     */
    public void setTotalGrupos(int value) {
        this.totalGrupos = value;
    }

}
