name: bilan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup java version
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build bilan project with maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true -X
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: bilan
          environment: bilan-stage
          version_label: ${{ github.SHA }}
          deployment_package: target/bilan-backend-0.0.1-SNAPSHOT.jar